apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: egypt-web
  namespace: travel-dream
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: egypt.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: egypt-web
                port:
                  number: 80
