apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tanstack-observatory
  namespace: tanstack-observatory
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: tanstack-observatory.mudid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tanstack-observatory
                port:
                  number: 80
