apiVersion: v1
kind: ServiceAccount
metadata:
  name: travel-dream
  namespace: travel-dream
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: travel-dream
  namespace: travel-dream
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travel-dream
  namespace: travel-dream
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: travel-dream
subjects:
  - kind: ServiceAccount
    name: travel-dream
    namespace: travel-dream
