apiVersion: v1
kind: Service
metadata:
  name: travel-dream
  namespace: travel-dream
  labels:
    app.kubernetes.io/name: travel-dream
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: travel-dream
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
